// Generated by CoffeeScript 1.7.1
(function() {
  document.addEventListener("DOMContentLoaded", function(event) {
    vid.addEventListener('loadedmetadata', function() {
      return this.currentTime = 50;
    }, false);
    return vid.addEventListener('canplay', function() {
      this.className = "melt";
      return this.play();
    });
  });

}).call(this);
